export default `CREATE TABLE IF NOT EXISTS email_list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email VARCHAR NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`;
